### ISSUE TITLE
Coin system

### ISSUE THREAD

**Issue by cdqwertz** [CasimirKaPazi/uforun#13]
What do you think about a coin system?
You get coins when you play a level so, you can buy new blocks to create your own levels.

**Comment by ObaniGemini** [comment]
I think it would be better to make has in many run games a "hidden coins" system : coins are hidden in the levels and you have to find them to get them (but this would be only for solo part).

Also your idea is very good IMO, and could make a very diversified server. Also maybe to claim for a place to build protected ?

**Comment by wilkgr76** [comment]
These could be in the form of dropped items (modded so they don't despawn) and "driving" over them picks them up into the users' inventory. Then use Lua to check the inventory. Also, set the hotbar to just 1 stack for easier visibility while racing.

**Comment by cdqwertz** [comment]
I think it would be easier with blocks...

Edit : **I am working on coins!**

**Comment by ObaniGemini** [comment]
Yes, and lag-less...

**Comment by wilkgr76** [comment]
@cdqwertz You're right. How will you keep track of coins, and display them to the user while racing? Also, it might be neat if they could be used for performance upgrades, different skins, etc.

**Comment by cdqwertz** [comment]
I uploaded a simple coin system, I created, now!
@wilkgr76 I think we could display them in the hud... , take a look at the xp mod of RPGtest :)
@wilkgr76 upgrades would be really cool!

PS : I will update the forum topic now :)

**Comment by wilkgr76** [comment]
@cdqwertz If there's going to be a lobby system, we could display the total number of coins in the lobby. Also: to store the number of coins even between server restarts, perhaps use something like the "db" mod?
[https://forum.minetest.net/viewtopic.php?f=9&t=9276](https://forum.minetest.net/viewtopic.php?f=9&t=9276)

**Comment by cdqwertz** [comment]
There will be a lobby system :)
I am working on a gamedata mod. It will store the coins :)

**Comment by wilkgr76** [comment]
This issue can now be closed.
