### ISSUE TITLE
Hotbar textures

### ISSUE THREAD

**Issue by cdqwertz** [CasimirKaPazi/uforun#14]
Could someone create a nice hotbar bg texture and a selected item texture?

**Comment by ObaniGemini** [comment]
@cdqwertz : Could you describe a little bit more ? A hotbar for what ? A selected item texture for what ? Do you have an idea on it ?

**Comment by cdqwertz** [comment]
something like this : https://github.com/minetest/minetest_game/blob/master/mods/default/textures/gui_hotbar.png

**Comment by ObaniGemini** [comment]
Ok do you want it more like minimalistic or others ? Do you have a style-guideline ?

**Comment by cdqwertz** [comment]
I think a minimalistic texture would be great :)

**Comment by wilkgr76** [comment]
Rounded edges? (I'm thinking of docker atm)

**Comment by cdqwertz** [comment]
ok

**Comment by wilkgr76** [comment]
![gui_hotbar_uforun](https://cloud.githubusercontent.com/assets/12093476/15241122/4570cb2e-1931-11e6-8d52-05334fdd479f.png)
Note that it is semi-transparent. I can remove the white semitransparentness.

**Comment by cdqwertz** [comment]
looks good :+1:

**Comment by wilkgr76** [comment]
@cdqwertz Adding pull request later. Please take a look in-game before submitting it though. Please!

**Comment by cdqwertz** [comment]
ok - have you tested it yet?

**Comment by wilkgr76** [comment]
@cdqwertz I have revised the texture a bit. The white doesn't fit very well.
![gui_hotbar_uforun](https://cloud.githubusercontent.com/assets/12093476/15245736/c85cdcd4-194b-11e6-98f1-7d9ee8635553.png)

**Comment by wilkgr76** [comment]
On the other hand, having a completely transparent texture would eliminate the need of hiding it during races...

Here's a snippet of it with the clear bar at the bottom: (The blue can be replaced with a different colour, needless to say)
![screenshot_20160513_205305](https://cloud.githubusercontent.com/assets/12093476/15245906/be46959a-194c-11e6-9b13-911226b20236.png)

**Comment by cdqwertz** [comment]
hmm, good idea.
Maybe we can change the texture when you play a level :)

**Comment by wilkgr76** [comment]
@cdqwertz Not possible I think... We could just empty the inventory/move the items out of the hotbar to hide it with the transparent one. Up to you.

**Comment by cdqwertz** [comment]
It is...

`player:hud_set_hotbar_image(texturename)`

**Comment by wilkgr76** [comment]
@cdqwertz Oh...

**Comment by wilkgr76** [comment]
Will make pull request as soon as I figure it out...

:soon:

**Comment by cdqwertz** [comment]
If you dont want to code that, I could also code that :)

**Comment by wilkgr76** [comment]
@cdqwertz As I am not familiar with the code, that will be appreciated. Where should the hotbar images go?

**Comment by cdqwertz** [comment]
in  uforun/mods/uforun/textures

**Comment by wilkgr76** [comment]
Ok, though so. Thanks :smile:

**Comment by wilkgr76** [comment]
Well...um...I should've cloned my fork, not the real repository...

> remote: Permission to CasimirKaPazi/uforun.git denied to wilkgr76.
> fatal: unable to access 'https://github.com/CasimirKaPazi/uforun.git/': The requested URL returned error: 403"

:sos: 
@cdqwertz What now?

**Comment by cdqwertz** [comment]
hmmm...
 [This](https://help.github.com/articles/removing-a-remote/) could work

**Comment by wilkgr76** [comment]
@cdqwertz Thanks :smiley_cat:

**Comment by wilkgr76** [comment]
@cdqwertz #20
