### ISSUE TITLE
Ufo model

### ISSUE THREAD

**Issue by cdqwertz** [CasimirKaPazi/uforun#16]
It would be really nice if someone could make a ufo model and a texture for it.

**Comment by wilkgr76** [comment]
How is the UFO mod's mesh licensed? We might be able to use this until we have something better.

**Comment by cdqwertz** [comment]
It isnt a mesh, thats the problem - I cant use a nodebox as a player model...

**Comment by wilkgr76** [comment]
?

Then what is the "ufo.x" and "ufo.blend" files?

**Comment by cdqwertz** [comment]
In which folder?

**Comment by wilkgr76** [comment]
models folder

**Comment by cdqwertz** [comment]
I cant find that folder....

**Comment by wilkgr76** [comment]
@cdqwertz @CasimirKaPazi https://github.com/Zeg9/minetest-ufos/tree/master/ufos/models

**Comment by wilkgr76** [comment]
See: #17

**Comment by benrob0329** [comment]
I've finally made a Github account, so expect a pull request by tomorrow (EST) with my model.

**Comment by benrob0329** [comment]
#18

**Comment by wilkgr76** [comment]
Can't this be closed now?

**Comment by wilkgr76** [comment]
@cdqwertz Thank you :smile_cat:

**Comment by wilkgr76** [comment]
#20
